image: "ghcr.io/oleksis/blackpythondevs.com:latest"
tasks:
  - name: Init and Post create command
    init: |
      cd /workspace/blackpythondevs.github.io
      sudo usermod -a -G rvm gitpod
      sudo chown -R gitpod /usr/local/rvm/gems/
      bundle install
    command: |
      sudo -i -u root
      cd /workspace/blackpythondevs.github.io
      sh /usr/local/post-create-bpdevs.sh
ports:
  - port: 4000
    onOpen: open-preview
    name: Jekyll

vscode:
  extensions:
    - ms-python.python
    - DavidAnson.vscode-markdownlint

workspaceLocation: "/workspace/blackpythondevs.github.io"
