image: "ghcr.io/oleksis/blackpythondevs.com:latest"
tasks:
  - name: Init and Post create command
    init: |
      sudo -i -u root
      cd /workspace/blackpythondevs.com
      bundle install
    command: |
      sudo -i -u root
      cd /workspace/blackpythondevs.com
      sh /usr/local/post-create-bpdevs.sh
ports:
  - port: 4000
    onOpen: open-preview
    name: Jekyll

vscode:
  extensions:
    - ms-python.python
    - DavidAnson.vscode-markdownlint
