blank_issues_enabled: true
contact_links:
  - name: Black Python Developers Maintainers Discussions
    url: https://github.com/BlackPythonDevs/.maintainers/discussions
    about: Please ask and answer questions here.
