name: Conference AutoResponder

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  add_comment:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Add initial comment to the issue
        uses: actions/github-script@v6
        if: ${{ github.event.action == 'opened' && startsWith(github.event.issue.title, '[CONFERENCE]') && contains(github.event.issue.labels.*.name, 'conference') }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            const comment = "Thank you for submitting this issue. A member of the triage team will review the information and followup on this request. There is no code action to be taken.";
              ...context.repo,
              issue_number: issueNumber,
              body: comment
            });

      - name: Add approved comment
        uses: actions/github-script@v6
        if: ${{ github.event.action == 'opened' && startsWith(github.event.issue.title, '[CONFERENCE]') && contains(github.event.issue.labels.*.name, 'conference_accepted') }}
        with:
          script: |
            const issueNumber = context.issue.number;
            const comment = "Your conference submission has been accepted. You will shortly see your conference on the website."

            github.rest.issues.createComment({
              ...context.repo,
              issue_number: issueNumber,
              body: comment
            });
