name: Generate and Upload Screenshots
# https://devblogs.microsoft.com/python/announcing-playwright-for-python-reliable-end-to-end-testing-for-the-web/
# https://github.com/marketplace/actions/run-playwright-tests

on:
  pull_request:
    types: [labeled]
    branches:
      - gh-pages

  workflow_dispatch:

jobs:
  test:
    if: ${{ github.event.label.name == 'design_change' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          python -m playwright install --with-deps chromium
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          # Run tests
      - name: Run Tests
        run: |
          python -m pytest -m design
      - name: upload images
        uses: actions/upload-artifact@v4
        with:
          name: page_screenshots
          path: test_images/
          compression-level: 9
