name: Playwright Tests
# https://devblogs.microsoft.com/python/announcing-playwright-for-python-reliable-end-to-end-testing-for-the-web/
# https://github.com/marketplace/actions/run-playwright-tests

on:
  push:
    branches:
      - gh-pages
  pull_request:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          python -m playwright install --with-deps chromium
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          # Run tests
      - name: Run Tests
        run: |
          python -m pytest
